title: Mighty Buda's Collection
theme: jekyll-theme-architect
email: jonathan.r.carpenter@gmail.com
description: A collection of notes, thoughts, recipes, music, and musings.
url: github.mightybuda.com
collections:
  recipes:
    output: true
  experiments:
    output: true